---
title: 嵌套切面
comment: false
editLink: false
prev: false
next: false
---

## 简介

**在`SpringBoot AOP`中,如果调用的方法内部调用了另外一个也使用了切面的方法,那这个被调用的方法的切面不会被执行.**

假设服务类中有如下两个方法:

```kotlin

@Service
class UserService {

    @Log("创建用户", AUTHENTICATION)
    override fun createUser(@LogItem("username", "用户名") token: Authentication) {
        if (!userService.existsUser(token)) {
            var user = HiUser()
            user.username = token.username
            user.anonymous = token.principal is AnonymousWebUserPrincipal
            createAccount(user)
            user = repository.save(user)
            userFreeAccountService.resetFreePoints(user.freeAccount!!)
        }
    }
    
    @Log("检查用户是否存在", AUTHENTICATION, returnLabel = "用户是否存在")
    override fun existsUser(@LogItem("username", "用户名") token: Authentication): Boolean {
        return repository.exists(QHiUser.hiUser.username.eq(token.username))
    
    }
}
```

现在为`@Log`注解创建一个切面:

```kotlin
@Aspect
@Component
class LogAspect {
    @Pointcut("@annotation(cn.dongjak.extension.log.Log)")
    fun logPoint() {
    }
    @Around("logPoint()")
    fun log(joinPoint: ProceedingJoinPoint, log: Log): Any {
        val startTime = System.currentTimeMillis()
        val result = joinPoint.proceed()
        val endTime = System.currentTimeMillis()
        val duration = endTime - startTime
        logService.log(log.value, log.level, duration, log.returnLabel, result)
        return result
    }
}
```

你会发现只有`createUser`方法的切面会被执行,而`existsUser`方法的切面不会被执行.

    这是由于 Spring AOP 使用的是代理模式，而代理只能拦截通过代理进行的外部方法调用

## 解决方案

可以通过`自我注入`的方式解决这个问题:

:::info
在此之前需要先将`spring.main.allow-circular-references`设置为`true`,否则会出现循环引用错误
:::

```java
@Service
public class YourService {

    @Autowired
    private YourService self;

    public void publicMethod() {
        // 这个方法通过代理对象调用，因此能够应用切面
        self.protectedMethod();
    }

    public void protectedMethod() {
        // ...切面应该在这里被触发
    }
}
```
